name: Atualizar Dados ODS

on:
  schedule:
    - cron: "0 2 * * *" # roda automaticamente todos os dias às 2h da manhã
  workflow_dispatch: # permite rodar manualmente também

jobs:
  atualizar-dados:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci || npm install
        
      - name: Verificar diretório de dados
        run: mkdir -p dados

      - name: Executar script de atualização de dados
        run: node js/atualizar-dados.js
        
      - name: Verificar alterações nos dados
        id: verificar-alteracoes
        run: |
          git status --porcelain dados/ | wc -l > alteracoes.txt
          ALTERACOES=$(cat alteracoes.txt)
          echo "total_alteracoes=$ALTERACOES" >> $GITHUB_OUTPUT
          echo "Total de alterações encontradas: $ALTERACOES"

      - name: Commit e Push dos dados atualizados
        if: steps.verificar-alteracoes.outputs.total_alteracoes != '0'
        run: |
          git config user.name "github-actions[bot]"  
          git config user.email "github-actions[bot]@users.noreply.github.com"  
          git add dados/*.json  
          git commit -m "Atualização automática dos dados ODS - $(date +'%d/%m/%Y')"
          git push
          
      - name: Exibir status - Sem alterações
        if: steps.verificar-alteracoes.outputs.total_alteracoes == '0'
        run: echo "✅ Nenhuma alteração nos dados foi detectada. Dados já estão atualizados!"
