name: Atualizar Dados ODS

on:
  schedule:
    - cron: "0 2 * * *" # roda automaticamente todos os dias às 2h da manhã
  workflow_dispatch: # permite rodar manualmente também

jobs:
  atualizar-dados:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Atualizar dados Mortalidade Infantil (exemplo IBGE)
        run: |
          curl "https://servicodados.ibge.gov.br/api/v3/agregados/793/periodos/-1/variaveis/104?localidades=N6[28]" -o dados/mortalidade_infantil.json

      # Adicione outros indicadores aqui seguindo o mesmo padrão acima

      - name: Commit e Push dos dados atualizados
        run: |
          git config user.name "github-actions"  
          git config user.email "github-actions@github.com"  
          git add dados/*.json  
          git commit -m "Atualização automática dos dados ODS" || echo "Nenhuma alteração para commitar"  
          git push
